### ISSUE TITLE
Consistently use `DiscreteDynamicalSystem` for discrete maps

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#123]
At the moment, some example systems are represented as `DiscreteDynamicalSystem`s which can be iterated. But some systems (e.g. autoregressive systems with lags) are generated by a function without an iterator, returning the orbits directly.

@datseris: Is there a good, easy way to keep track of lagged influences for a `DiscreteDynamicalSystem`? Do I simply need to create a higher-dimensional state vector which keeps track of past states too, if I want lagged influences?

**Comment by Datseris** [comment]
Hm, there is no good way to access pass states while evolving the system, mostly because the design decision was made to not keep this information (and save memory) since the main of DynamicalSystems.jl is deterministic systems.

But if you really need it, I guess the simplest way would be to make the "parameters" of the system have an extra parameter, a mutable vector, that stores as many past values as you need, e.g. the past 4 or past 10 or past N values. This seems to me the "cleanest" way to do this at the highest level, without messing with any of the internals. The equations of motion would then read this vector, use the past, and then modify the vector to store one more element from the past. Since the "current step" `n` is part of the equations of motion, you can always tell at which point in the evolution you are.

**Comment by kahaaga** [comment]
Ok, thanks! That sounds like a reasonable approach. It didn't cross my mind that the parameters could be mutable. 

I'll re-do the lagged systems using your proposed approach, so that all systems are represented the same way.
