### ISSUE TITLE
Tag 1.0

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#144]
Hi @Datseris,

Now the master branch is ready for a code review, if you wanted to have a look before I tag 1.0. 

- The GitHub workflow (CompatHelper, TagBot) is also working properly now. 
- Old files are removed.
- The readme is updated. The dev docs now link to the master branch, while the stable docs link to the old docs (will be updated once v1 is tagged).

**Comment by Datseris** [comment]
great thanks, I'll post things I see here.

**Comment by Datseris** [comment]
`crossmap` implementation uses `w` both for theiler window and for weights leading to type instability. A different symbol needs to be used.

Furthemore, instead of initializing ytilde as a copy, you can initialize it as zeros. Then, you can simply add `n1 == 0 && continue` instead of using 0 weights. After all 0 weights give the value 0 to the yhat

**Comment by kahaaga** [comment]
Anything else that needs immediate fixing, @Datseris? If not, I suggest that we tag v1.0 straight away. We can keep this issue open to keep track of any issues that (inevitably) arise once a tag is released and users try to install it, and patch release as needed.

**Comment by Datseris** [comment]
Sounds good, go ahead. Had a final look at the docs but didn't spot something obvious. It's probably better if users open new issues instead.

**Comment by kahaaga** [comment]
@JuliaRegistrator register
