### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#152]
Let's discuss here possible logo ideas/suggestions. Square logo is the first thing to nail, for the documentation website.

**Comment by kahaaga** [comment]
There definitely should be a square logo. I'll see if I can come up with some nice suggestions.

I also wanted a flashy animation for the docs/readme, maybe with a set of iterated time series where the dynamical coupling changes with time. Next to those time series, display some causality measure computed on those time series. In addition, maybe set simple graph with arrows (that switch over time) indicating directionality returned by the analysis. The value of the causality measure could be displayed as number above the edges in the graphs. I'll make a suggestion and we can see if you also like it!

**Comment by Datseris** [comment]
I was thinking something along the graph in the CCM nature paper and next to the graph some produced timeseries, and maybe some arrows connecting the timeseries... I'll post something here once I have more free time to sketch something!

**Comment by kahaaga** [comment]
I made a simple preliminary logo that is now visible in the dev docs. Since the repo will include independence testing and causal graph stuff, a graph-like logo felt natural. I did in the same style as the DynamicalSystems logo. The square version is just the large logo minus the text.

Our group approves, but we're not locked to any specific design. What do you think, @Datseris? 

<img width="817" alt="Skjermbilde 2023-02-07 kl  16 26 43" src="https://user-images.githubusercontent.com/5237566/217287975-d999fc68-e495-43e4-8f0c-a10b4c93f772.png">

**Comment by Datseris** [comment]
Very nice, but I am not sure about twhat the diagonal line means? Maybe make it directed and not touching like the other two? This way you can also use the right part as an icon in the docs.

**Comment by kahaaga** [comment]
I didn't think about any meaning when making the logo, or the diagonal line - I just thought it looked nice. But a diagonal line without arrows is standard notation for an undirected edge (i.e. in causality terms, the influence may go both ways). It's essentially the same as the bidirectional arrow. 

We might as well stick to meaningful notation, though, because it's weird to have two different symbols for the same thing.
I'll adjust it to a directed, non-touching arrow.

**Comment by kahaaga** [comment]
<img width="239" alt="logo" src="https://user-images.githubusercontent.com/5237566/217662796-5f298276-4b6f-4a74-b3d4-4be1e40b99e0.png">
<img width="674" alt="logo_large" src="https://user-images.githubusercontent.com/5237566/217662803-29cceb06-967c-4b92-9800-3b8a08c701ab.png">

What do you think? I'm not super happy with the middle arrow, but I think it'll do for now.

**Comment by Datseris** [comment]
I think it is fine as it is, but make it without background for the icon (top)! You could also make it in black mode,, by making the background color the same as the docpages background color. This is what I did for Agents.jl: https://juliadynamics.github.io/Agents.jl/stable/

The color is: https://github.com/JuliaDynamics/doctheme/blob/master/juliadynamics-style.scss#L16

**Comment by kahaaga** [comment]
Then we'll stick to the current design. I'll make a black variant and a transparent variant.
