### ISSUE TITLE
tutorial examples for each estimator

### ISSUE THREAD

**Issue by Ziaeemehr** [JuliaDynamics/CausalityTools.jl#170]
Helli,
I am just starting to use this package, thanks for sharing.
I am trying to do some test on each estimator and figure out the settings,
but I don't see much examples and the documentations also does not that much information to use each spesific one.

for example: 

```julia
N = 1000
source = rand(0:1, N)
destination = [0; source[1:end-1]]

b = RectangularBinning(5)
mi_estimator = VisitationFrequency(b)
mutualinfo(source, destination, mi_estimator)
# 0.00017
```

I was expecting to get a larger value of mutial information about 1bit for lag 1.
I also could not find a working example for :
```julia
Kraskov2(k::Int = 1; metric_x = Chebyshev(), metric_y = Chebyshev()) <: MutualInformationEstimator
```

**Comment by Datseris** [comment]
Yes to the documentation, and please be aware that documentation Pull Requests is the best thing a beginner can do. A beginner is the best person to improve the documentation, because they can see the documentation with a fresh eye, which the developers cannot. So please consider opening Pull Requests here and there :)

The example is working as it should be. The mutual information of two streams of random numbers should be as close to zero as computationally possible. Why would you expect something else?

**Comment by Datseris** [comment]
Your `source` and `destination` vectors are as uncorrelated as possible. They are both uniformly distributed numbers in 0-1.

**Comment by kahaaga** [comment]
Adding on the comments from @Datseris: 

Mutual information is `I(X, Y) = H(X) + H(Y) - H(X, Y)`, where `H` is entropy. Denote by `Px` and `Py` the marginal distributions for `X` and `Y`, and `Pxy` the joint distribution.

The `VisitationFrequency` estimator with a `RectangularBinning` given an integer (`5` in your case) will divide the input data into 5 non-overlapping bins, count visitations in those bins, and compute mutual information from the estimated marginal probability distributions. With your input data, that means computing the entropy over uniform distributions, because

- for the marginal distributions `Fx` and `Fy`, all `0`s end up in exactly one bin, and all `1`s end up in another bin. When `N → ∞`, there will be an equal number of visitations to each bin, so when normalizing, we get the probabilities `Px = [0.5, 0.5]` and `Py = [0.5, 0.5]`. *Notice that any number of bins >= 2 would give the same mutual information, because your data is binary, and will only occupy precisely two bins, the rest being empty*.
- For the joint distribution `Fxy`, using a similar equal argument, we get four non-empty states, call them `(0,0), (1, 1), (1,0), (0,1)`. When `N → ∞`, each of these states will be visited with equal frequencies, so we get probabilities `Pxy = [0.25, 0.25, 0.25, 0.25]`.

Computing either by hand, or by using `Entropies.jl` (like I do here), we get 

```julia
using Entropies
Px = [0.5, 0.5]
Py = [0.5, 0.5]
Pxy = repeat([0.25], 4)
```
```julia
julia> genentropy(Probabilities(x)) + genentropy(Probabilities(x)) - genentropy(Probabilities(repeat([0.25], 4)))
0.0
```

**Comment by Ziaeemehr** [comment]
Thanks for quick replay, 
source and destination the same array shifted by one element (0 added at the beginning).
I get the following results by sweeping over delay for mutual information from infodynamics package by lizier/JIDT package. I would liked to reproduce the same here.
![mi_lag](https://user-images.githubusercontent.com/7780103/190922209-8f41140a-b94f-4518-98dc-a8676054aa5d.png)
The algorithm is `MutualInfoCalculatorMultiVariateKraskov1`, but I could not use the same algorithm from CausalityTools.

**Comment by kahaaga** [comment]
> Thanks for quick replay,
source and destination the same array shifted by one element (0 added at the beginning).
I get the following results by sweeping over delay for mutual information from infodynamics package by lizier/JIDT package. I would liked to reproduce the same here.
> The algorithm is MutualInfoCalculatorMultiVariateKraskov1, but I could not use the same algorithm from CausalityTools.

I'm not familiar with this particular estimator, so I can't elaborate on why you're getting this particular result. Reproducing this result would be nice, though. Could you please provide the complete example code you ran to produce the figure above, as well as the version of the `lizier/JIDT` package you used?

**Comment by Ziaeemehr** [comment]
```python
import numpy as np
import pylab as pl
from jpype import *
import random
import math
import sys
# Our python data file readers are a bit of a hack, python users will do better on this:
sys.path.append(".")


jarLocation = "../infodynamics.jar"
startJVM(getDefaultJVMPath(), "-ea", "-Djava.class.path=" + jarLocation)

# source = [normal(mu, sigma) for r in range(nObv)]
# destination = [0] + [sum(pair) for pair in zip([covariance*y for y in sourceArray[0:nObv-1]],
#                                              [(1 - covariance) * y for y in [normal(0, 1) for r in range(nObv - 1)]])]                                                           
# source2 = [normal(mu, sigma) for r in range(nObv)]

N = 1000
lags = range(15)
numSurrogates = 5
source = [random.randint(0, 1) for r in range(N)]
destination = [0] + source[0:N-1]
# source = [random.randint(0, 1) for r in range(N)]


# 1. Construct the calculator:
calcClass = JPackage("infodynamics.measures.continuous.kraskov").MutualInfoCalculatorMultiVariateKraskov1
calc = calcClass()
calc.setProperty("NUM_THREADS", "4")


result = []

for lag in lags:
    calc.setProperty("TIME_DIFF", str(lag))
    calc.initialise()
    calc.setObservations(source, destination)
    # calc.setObservations(destination, source)
    mi = calc.computeAverageLocalOfObservations()
    NullDist = calc.computeSignificance(numSurrogates)
    NullMean = NullDist.getMeanOfDistribution()
    NullStd = NullDist.getStdOfDistribution()

    result.append([mi/math.log(2), NullMean, NullStd])


result = np.asarray(result)
pl.plot(lags, result[:, 0], marker="x", label="MI")
pl.errorbar(lags, result[:, 1], yerr=result[:, 2])
pl.xlabel("lags")
pl.ylabel("MI (bits)")
pl.savefig("mi_lag.png")
pl.show()
```

**Comment by kahaaga** [comment]
Thanks, @Ziaeemehr. I'm not familiar with Lizier's framework, so I'll have to look at the documentation and source code to understand what's going on. That's probably not done in an instant, but I'll get on it as soon as possible. 

I'm guessing the data is embedded using some automated procedure for selecting embedding variables. If that is the case, the mutual information you get will depend on that embedding. You can verify that the embedding affects the computed mutual information for yourself by manually embedding your input data and trying to use the straight-forward histogram-counting estimator `CountOccurrences` from Entropies.jl. For example:

```julia
julia> x = rand(0:1, 1000);
julia> y = [0; x[1:end-1]]
```

If embedding both time series using a 3D embedding with lag 1, we get the following mutual information:

```julia
τs = (-2, -1, 0)
julia> X = genembed(x, τs)
julia> Y = genembed(y, τs)
3-dimensional Dataset{Int64} with 998 points
 0  1  1
 1  1  1
 1  1  0
 1  0  1
 0  1  1
 1  1  0
 1  0  0
 0  0  1
 0  1  1
 1  1  1
 ⋮
 0  1  1
 1  1  0
 1  0  0
 0  0  1
 0  1  0
 1  0  0
 0  0  0
 0  0  1
 0  1  1
```

```julia
julia> mutualinfo(X, Y, CountOccurrences())
0.033696288146520814
```

Using a different embedding on the same data, the mutual information is different. 

```julia
julia> τs2 = (-8, -5, 0)
(-8, -5, 0)
julia> X = genembed(x, τs2); Y = genembed(y, τs2); mutualinfo(X, Y, CountOccurrences())
0.028277258779307424
```

There are plenty of algorithms for estimating embedding dimensions and lags from time series in DynamicalSystems.jl if you want to experiment further with this.

Note that I didn't specify a random number generator here, so you won't get the exact same numbers when running the example. Also, in this example, I estimate mutual information by naive counting of histograms (because your data is binary), not using the nearest-neighbor based Kraskov estimator (which is better to use for real-valued data). What one can say in general is that estimators have different biases, so estimated mutual information values will be different.

I'll tag you here when I've had a change to take a closer look at the JIDT package example.

**Comment by Datseris** [comment]
>  source and destination are the same array shifted by one element (0 added at the beginning).

Yes, but this "same array" is just random numbers, so these two "similar arrays" should have 0 mutual information. If you're using some software that gives you significantly non-zero mutual information, that software has implemented its calculations wrongly.

**Comment by Ziaeemehr** [comment]
Thank you for your extensive answers. :+1: 
If that's not too much trouble I would also appreciate providing simple working examples for each estimator. That definitely accelerates new users learning curves.

**Comment by Datseris** [comment]
Have you tried doing 
```julia
mi_estimator = Kraskov2(k=1)
mutualinfo(source, destination, mi_estimator)
```
and it didn't work?

**Comment by kahaaga** [comment]
@Datseris note that `Kraskov2(k=1)` won't work, you need to do `Kraskov2(1)`. The number of neighbors is not a keyword argument.

**Comment by kahaaga** [comment]
I looked into this a bit further. For integer-valued inputs, the `Kraskov2` estimator gives infinite values

```julia
julia> x = rand(0:1, 1000); y = [0; x[1:end-1]]; mutualinfo(x, y, Kraskov2(1))
Inf
```

while the `Kraskov1` estimator does not:

```julia
julia> x = rand(0:1, 1000); y = [0; x[1:end-1]]; mutualinfo(x, y, Kraskov1(1))
7.484470860550341
```

From a quick glance at the documentation for the framework linked above, it seems that they add some random noise to the data before counting neighbors that avoids this situation.

**Comment by Datseris** [comment]
> From a quick glance at the documentation for the framework linked above, it seems that they add some random noise to the data before counting neighbors that avoids this situation.

Bad practice in my humble opinion... One should explicitly ask the user to do so and minimize the behind-the-scenes magick...
