### ISSUE TITLE
Release one more 1.X or go directly to 2.0?

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#237]
@Datseris We're getting reeaaally close to finishing our review now. Therefore, I'm wondering what to do about the versions when transitioning to 2.0.

What have you done in terms of deprecations when releasing new major versions in the other JuliaDynamics packages? According to Semver, when breaking changes occur, one should release at least one minor version that deprecates old functionality. But should that version be a final 1.X (and deprecations are removed in 2.0), or 2.0 (and deprecations are removed in 2.1)? 

If releasing a final 1.X, that will essentially be V2.0, but with deprecations.

**Comment by kahaaga** [comment]
Perhaps tagging a final 1.X that is locked to v2 with respect to DelayEmbeddings and DynamicalSystemsBase? Then 2.0 will relate to v3 of these packages?

**Comment by Datseris** [comment]
> According to Semver, when breaking changes occur, one should release at least one minor version that deprecates old functionality.

If you can deprecate functionality, you can do so in the next major release as well. At least that is what I have done. The problem is what you do when it is not possible to deprecate something. E.g., I changed `trajectory` to return both the dataset and the time vector. It is not possible to deprecate this change. 

In any case, I have not tagged anything in between. Last package versions are as shown in the frozen latest release of DynamicalSystems.jl: 

![image](https://user-images.githubusercontent.com/19669089/219393643-b35b262b-23f9-4319-9127-0b5fe6fe81f8.png)

I am tagging v3 everywhere at the moment. THings that can be deprecated, I have already included in the new version. Things that cannot are listed in the changelog as breaking.

**Comment by kahaaga** [comment]
I've already released a version-locked V1.6 here, so I think I'll just go for the same approach then:
- Tag CausalityTools V2.0 directly, depending on DelayEmbeddings v3.0 and DynamicalSystemsBase v3.0.
- Deprecate changes that can be deprecated, and remove them in a later minor release.
- List any breaking changes in the changelog.

**Comment by Datseris** [comment]
Why would DynamicalSystemsBase v3.0. be a dependency of the package?

**Comment by Datseris** [comment]
You only need DelayEmbeddings v2.7 actually. There was nothing breaking in that package so I didn't push the major release. I am releasing 2.7 soon.

**Comment by kahaaga** [comment]
> Why would DynamicalSystemsBase v3.0. be a dependency of the package?

Because of the example systems. Nothing else. These will be moved into a separate package at some point, after I've thought carefully through my plan for a systematic parameter resampling and sensitivity testing system. But I don't have time to deal with that now, so `DynamicalSystemsBase` is a dependency for now

**Comment by Datseris** [comment]
> Because of the example systems. Nothing else.

I don't think providing example systems is a good idea for long term. You should use the package in the documentation and create the example systems on the spot only. But DYnamicalSYstemsBase should not be a direct dependence. FUrthermore, you can just put these example systems in PredefinedDynamicalSystems.jl and call that (again, only in the doc builds).

(The reason PredefinedDynamicalSystems.jl exists is because I realized that it is just a bad idea to use predefined systems for anything else besides on-the-spot examples. All the tests that used predefined systems have also been refactored to define systems on the spot)

**Comment by Datseris** [comment]
Oh, also DynamicalSystemsBase.jl now has OrdinaryDiffEq.jl as a dependency which is quite heavy, one more reason to not depend on it.

**Comment by kahaaga** [comment]
> I don't think providing example systems is a good idea for long term.

Yes, I agree. They should be in a separate package.

>  But DYnamicalSYstemsBase should not be a direct dependence. FUrthermore, you can just put these example systems in PredefinedDynamicalSystems.jl and call that (again, only in the doc builds).

Unfortunately, some of the systems here aren't directly compatible with `DiscreteDynamicalSystem`, because some of the processes have memory beyond one time step. So we'll have to think about a way to implement that functionality systematically in PredefinedDynamicalSystems.jl.

Here, this is solved by defining the systems as types that have mutable containers, whose type instances are passed to `DiscreteDynamicalSystem` as the parameter container. 

> Oh, also DynamicalSystemsBase.jl now has OrdinaryDiffEq.jl as a dependency which is quite heavy, one more reason to not depend on it.

Yep, makes sense. The plan is to drop the example system from this package, but due to the issues described above, it will happen in a 2.X release, not for the 2.0 version, because there's some work involved to implement a good interface for the memory-based systems.

**Comment by Datseris** [comment]
> because some of the processes have memory beyond one time step. 

At the moment you can use [`ArbitrarySteppable`](https://juliadynamics.github.io/DynamicalSystemsBase.jl/dev/#ArbitrarySteppable) for that, but in the long term I guess a dedicated type cna be created. `DynamicalSystem` now defines a generic extendable interface so it shouldn't be hard. Please open an issue at DYnamicalSystemsBase,jl?

**Comment by kahaaga** [comment]
> > because some of the processes have memory beyond one time step.
> 
> At the moment you can use [`ArbitrarySteppable`](https://juliadynamics.github.io/DynamicalSystemsBase.jl/dev/#ArbitrarySteppable) for that, but in the long term I guess a dedicated type cna be created. `DynamicalSystem` now defines a generic extendable interface so it shouldn't be hard. Please open an issue at DYnamicalSystemsBase,jl?

Ah, excellent! I hadn't seen that. I'll open an issue both here and in DynamicalSystemsBase.jl, so it is on the todo-list.
