### ISSUE TITLE
Suggestions for documenation improvements 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#94]
Hi there,

seems you guys have put alot of work into CausalityTools.jl. Seems great, you have really done a wonderful job implementing so many different algorithms.

I was going through your docs, because I wanted to learn more about transfer entropy and deducing causal relations and I think you could benefit by the following suggestions.

# Overview for beginners
For someone that doesn't know the CausalityTools.jl code base, it is easy to get lost. There are 100 if not 1000 total pages on the side bar. What is missing is a small, high-level overview of how to use this package, or to be more specific in which page of the sidebar to go if you need to learn/do a specific thing.

(notice that the "Goals" bullet list does not achieve this)

I just wanted to calculate transfer entropy between two timeseries, but you would be surprised to hear I wasn't really sure how to proceed with your packages. Sometimes having 1000s of options can overwhelm a beginner. For example, there is no high-level page in the sidebar called "Transfer Entropy".

The "Overview" sub pages of E.g. Surrogate data and Causality tests are great and achieve exactly what I describe here. But they only do it for their specific aspect. What is missing is an "overview" of the entire ecosystem.

# Return value of `causality` etc.
For such a central function like `causality`, its return value should be explicitly stated in the documentation string. The same should happen for all central / important functions. Their return type should be stated as explicitly as possible.

# Code output

There are a lot of examples in many pages, but to see the output of the examples the only option is to run the code. E.g.: https://kahaaga.github.io/CausalityTools.jl/dev/causalitytests/causality_from_time_series/#causality_time_series-1

I'd recommend to use Documenter.jl more and show code output. I can see that you already do this here: https://kahaaga.github.io/CausalityTools.jl/dev/worked_examples/worked_example_transferentropy/ , so you know how to do this. I just want to point out that seeing more code output would probably help alot.

Another point here is that for many examples (in fact every page I've checked so far in the Tutorials/examples besides the TE) have code that results in errors and thus the documentation is not built properly. Please consider updating/fixing this.

# Don't hide `using` statements
Which packages are used in what example is extremely important information that should not be hidden in a Documenter `@setup` block.

**Comment by Datseris** [comment]
Maybe it is worth parallelizing https://kahaaga.github.io/TimeseriesSurrogates.jl/latest/ here, which has a marvelous documentation very much welcoming for beginners.

**Comment by kahaaga** [comment]
Hi there, @Datseris! 

Thanks for the detailed feedback. This is very useful! Developing this package is part of my thesis work, and I'm planning to submit a small JOSS paper on it before submitting the thesis. The last hurdle before doing so is precisely getting the documentation to a more beginner-friendly state. 

I hope to have time to get the documentation improvements finished during Christmas holidays. If you should have any more suggestions in the meanwhile, please feel free to mention them here, so I'm sure to remember to include them.

I'll start with getting a few simple examples up for transfer entropy, so you can get started with your experiments!

A small tick list:

## High level overviews

- [ ] Adding high-level pages on the different causality detection methods.
- [ ] Adding an overview page, maybe with common use cases, pointing the user to the correct documentation.

## Tutorials, using Documenter

- [ ] Use Documenter for the tutorials, and have at least
- [ ] At least one example tutorial for each of the methods on time series.
- [ ] At least one example tutorial for each of the methods on time series with uncertainties.
- [ ] Examples should be complete (show which packages are being used).

**Comment by Datseris** [comment]
Maybe one more thing to consider is linking textbooks or review articles on causal inference or transfer entropy in general. It is of course exceptional that you cite the source of each algorithm, but citing a more newcomer-targeting textbook/review would also help. You do cite a review article on timeseries surrogates for example.

**Comment by Datseris** [comment]
I am back to give more feedback after I've seen that there have been quite huge improvements and changes to the documentation. I think everything has become very nice, and the way to improve further can be summarized in the following points:

* Reduce the amount of over-all nesting and content separation. What I mean by that is that at the moment there are many (maybe too many) different pages. Many of them can be grouped into one. To give an example, have a look at: https://kahaaga.github.io/CausalityTools.jl/dev/causalitytests/NearestNeighbourMITest/ this page is nested in four (!!) nesting levels, starting from "Estimating causality" to Causality Tests to Transfer entropy to the current page.
* Reduce amount of organizational information (put it all in one place). If one looks at a page from the docs, one typically sees something like: 
![image](https://user-images.githubusercontent.com/19669089/73198042-afb0ef00-4132-11ea-9413-446aa7c6526e.png) in red I've circled the amount of organizational information, which is in three different parts. Since it is still early enough, I'd recommend to build documentation via Documenter's simple HTML approach where all organization happens on the left bar of the screen. 
* THink about what should be part of the public api and what not. Some things may not be really important for a front end user, but only for a developer. For example I could imagine that knowing the abstract types of the Transfer entropy estimators, as well as their subtypes, is not immediatelly useful and could be removed from here: https://kahaaga.github.io/CausalityTools.jl/dev/transferentropy/TE_estimators/ 
* (If possible) reduce the total amount of content: if something can have its own dedicated documentation, it make sense to leave it as is. E.g. TimeseriesSurrogates has docs but it is replicated here. 

In general I think all my comments align to one goal: making the docs _smaller_. If something can be made smaller without losing content (or with losing very little), it is preferable: it makes it much easier to go through.

What do you think about switching the documentation to Documenter.jl? I could make a PR that does this.

**Comment by kahaaga** [comment]
Thanks again for putting so much effort into this! Your comments are very helpful. It can be hard to see how the documentation looks from the outside when it's already internalized, so this helps to realize how much clutter comes with too many options! 

### General comments 

- **Reduce the amount of over-all nesting and content separation.** I whole-heartedly agree. 
- **Think about what should be part of the public api and what not**. I also agree - some of the documentation is not necessary to expose to the end-user. I will try to trim some away.
- **Remove "useless" content or pages**. Yes, I agree, no need to list the tutorials when it is already being done in the menu.
- **Reduce the total amount of content**. I also agree. Much of the clutter comes from too much information that in some cases (like for TimeseriesSurrogates.jl) is redundant.

## Using the simpler documentation layout

I looked through the DynamicalSystems.jl documentation again, and I both agree and disagree that a simpler layout should be used. There is a trade-off here. On pages with little information, the right-sidebar in the `material` theme is of little use. On pages with a lot of information, however, the right sidebar is very useful (for example, on the front page of the DynamicalSystems.jl docs, the right sidebar immediately guides me to relevant sections, such as contributing, citing, etc..) 

If going for a simpler layout, one alternative is to make some adjustments to the `material` template, removing the right sidebar completely. I am guessing this will take some more work than simply switching to the html-based Documenter.jl layout.

I can try to see for myself how the documentation looks when using the html-based layout. I guess it's just a matter of re-organizing menus in the `make.jl` file instead of in the `mkdocs.yml` file, @Datseris?

I've already done significant improvements to the documentation for the 1.0 release that are not published yet. These should not be far away. I will also try to take into consideration your additional suggestions above. 

If you have further suggestions after my documentation updates are published, you could make a PR for that then. Does that sound reasonable, @Datseris?

**Comment by Datseris** [comment]
I am happy that we are almost entirely on the same page, which is not always the case. This is great. 
I get your comments about navigation. I must admit that I am not as fond of the DynamicalSystems.jl docs as you are, and if it had less users I would in fact switch to documenter :P 

Here is what I propose: you push the changes that you are currently doing on master (when you feel you are done with the in a sufficnet degree), and then I make a PR that changes it to Documenter  so you can see how it looks? I have a lot of familiarity with documenter already and it will be quite fast for me.

**Comment by Datseris** [comment]
To quickly clarify something: I am not saying to remove the right-hand side bar with Documenter. Documenter also has it, but it is also in the left side, along with the main navigation. Having all navigation information at one place only is more powerful that what you'd initially think.

**Comment by kahaaga** [comment]
Sounds like a plan. I will ping you here when I push my final documentation improvements, then we can start experimenting with the Documenter.jl layout.

**Comment by Datseris** [comment]
@kahaaga have a look at the new documentation page of DynamicalSystems.jl here : https://juliadynamics.github.io/DynamicalSystems.jl/dev/ 

in fact, _all_ JuliaDynamics packages have the same documentation theme now. It is still beautiful, but it is much more readable.

**Comment by kahaaga** [comment]
That theme looks very nice indeed! Nice job 👍  The docs here should follow the same structure. That avoid too much nesting and makes everything easier to find. Excellent!

**Comment by Datseris** [comment]
If you move forward with joining JuliaDynamics, it is very easy to get the same theme. All repositories centrally install doc theme from here: https://github.com/JuliaDynamics/doctheme
